export interface Language {
    language: string;
    specify?: string; //becomes required if language === "Other"
}

export interface Languages {
    primary: Language;
    secondary?: Language;
}

export interface TravelRestriction {
    travel_restriction: boolean;
    restriction_reason?: string; //becomes required if travel_restriction true
}

export interface Country {
    country: string;
    other_country?: string; //becomes required if country === "Other"
}

export interface ContactMethod {
    method: string;
    other_method?: string; //becomes required if type === "Other"
}

export interface ContactPoint {
    type: ContactMethod;
    value: string;
}

export interface ContactPoints {
    primary: ContactPoint;
    secondary?: ContactPoint;
}

export interface SubmissionEntry {
    id: string; //guid generated by the system, not visible
    create_time: Date; //not visible Date.now()
    last_name: string; 
    first_name: string;
    full_name: string; //first_name + ' ' + last_name
    country: Country;
    gender: string;
    spoken_languages: Languages;
    dob: Date;
    valid_passport: boolean; //would rephrase the question: Do you own a valid passport issued by your country? 
    travel_restriction: TravelRestriction;
    contact_points: ContactPoints;
    user_id?: string;
    video_uri?: string;
}

export interface Entry extends SubmissionEntry {
    //here we need to add all atributtes related to managing the entry
}